import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/home-page/header";

const artDecoNormal = localFont({
  src: "./fonts/145d7d15e4d79baa-s.p.woff",
  display: "swap",
  variable: "--font-art-deco-normal",
});

const artDecoSemibold = localFont({
  src: "./fonts/1927f68609cd9595-s.p.woff",
  display: "swap",
  variable: "--font-art-deco-semibold",
});

const artDecoCondensedBold = localFont({
  src: "./fonts/7c47f8730b74dd15-s.p.woff",
  display: "swap",
  variable: "--font-art-deco-condensed-bold",
});

const artDecoBold = localFont({
  src: "./fonts/67cd960e7f9dc604-s.p.woff",
  display: "swap",
  variable: "--font-art-deco-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased custom-scrollbar ${artDecoNormal.variable} ${artDecoSemibold.variable} ${artDecoCondensedBold.variable} ${artDecoBold.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
